<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class recinto extends Model
{
    protected $fillable = [
        'nombre',
        'designedEspecies',
    ];

    public function animals()
    {
        return $this->hasMany('App\Models\animal');
    }
}
